### PR TITLE
fix: add disconnectedCallback() lifecycle method to unmount map

### LINKED ISSUE #96: Unmount map
Calling `map.dispose()` when the custom element unmounts might help making sure stale event handlers don't stick around. This could be implemented by setting `this.map = map;` after https://github.com/theopensystemslab/map/blob/main/src/my-map.ts#L179, and then later after https://github.com/theopensystemslab/map/blob/main/src/my-map.ts#L437, adding the following method on the class instance:

```ts
  disconnectedCallback() {
    this.map?.dispose();
  }
```

### PR DESCRIPTION
**Pull request by jessicamcinchak**
fixes #96 

:crossed_fingers: this might/should fix planx bugs described here https://github.com/theopensystemslab/planx-new/pull/704

https://lit.dev/docs/components/lifecycle/#content

### CODE REVIEW

File: src/my-map.ts [hunk 1]
```diff
@@ -204,6 +208,9 @@ export class MyMap extends LitElement {
       }),
     });
 
+    this.map = map;
+    this.performUpdate();
```
Comment (jessicamcinchak) [inline src/my-map.ts:212]: `this.performUpdate()` feels a bit odd/wrong, but clears up this Lit console warning introduced when setting this.map

Screenshot from 2021-12-11 12-05-02

maybe better approach, or just unnecessary? map behaves as expected with or without this explicit update it seems

File: src/my-map.ts [hunk 2]
```diff
@@ -204,6 +213,9 @@ export class MyMap extends LitElement {
       }),
     });
 
+    this.map = map;
+    super.performUpdate();
```
Comment (jessicamcinchak) [inline src/my-map.ts:217]: calling `performUpdate()` here feels a bit odd, but clears up this Lit console warning introduced when setting this.map - any ideas for better approach? docs seem spotty on this topic

Screenshot from 2021-12-11 12-05-02

**Comment by jessicamcinchak** [comment]
[About the property map returned two unrelated polygons](https://trello.com/c/6nVeR3jp/1619-about-the-property-map-returned-two-unrelated-polygons)

**Comment by jessicamcinchak** [comment]
[Super zoomed out map on 'find property'](https://trello.com/c/YrIzKiXz/1569-super-zoomed-out-map-on-find-property)

**Comment by jessicamcinchak** [comment]
[Map remembers a previously searched property](https://trello.com/c/vMr17Jdy/1538-map-remembers-a-previously-searched-property)

File: src/my-map.ts (hunk 2 above)
Comment (peterszerzo) [reply src/my-map.ts:217]: Would it help to just put `this.map` on the class instance as opposed to setting it as a reactive internal state with the `@state` decorator? The lit docs seem to not mention this as an option but I have a feeling the way `this.map` is used does not need any kind of reactivity (more like a `useRef` than a `useState` to borrow from React lingo).

File: src/my-map.ts [hunk 3]
```diff
@@ -160,9 +160,18 @@ export class MyMap extends LitElement {
   @property({ type: Boolean })
   useScaleBarStyle = false;
 
+  // internal reactive state
+  @state()
```
Comment (peterszerzo) [inline src/my-map.ts:164]: What I mean by the comment on the `performUpdate` - is this line here necessary?

File: src/my-map.ts [hunk 4]
```diff
@@ -230,6 +242,8 @@ export class MyMap extends LitElement {
       }
     };
 
+    // this is an internal event listener, so doesn't need to be removed later
+    // ref https://lit.dev/docs/components/lifecycle/#disconnectedcallback
```
Comment (peterszerzo) [inline src/my-map.ts:246]: Are you sure you get away with not having to clean this up if you didn't use their `render()` method with the `html` tagged template literal?

File: src/my-map.ts (hunk 2 above)
Comment (jessicamcinchak) [reply src/my-map.ts]: oh that's clever - i had definitely been following doc patterns and assuming every property should use a decorator, but this works (meaning, I can remove `performUpdate()` without prompting any lifecycle warnings)

File: src/my-map.ts (hunk 3 above)
Comment (jessicamcinchak) [reply src/my-map.ts]: removed now!

File: src/my-map.ts (hunk 4 above)
Comment (jessicamcinchak) [reply src/my-map.ts:244]: mostly sure :upside_down_face: the button & it's attached listener seem to be fully encapsulated in the map's shadow DOM on inspection, and the docs say "By default, a bubbling custom event fired inside shadow DOM will stop bubbling when it reaches the shadow root." so I _think_ that means it can be considered "internal" & shouldn't prevent the map from unmounting? 

https://lit.dev/docs/v1/components/events/#add-event-listeners-after-first-paint

Comment (peterszerzo) [reply src/my-map.ts:244]: Oh right, that makes sense!

**Review by DafyddLlyr — APPROVED** [review]
👍
